name: carispot
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/database/database.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
